[tool.poetry]
name = "openrpc-client-generator"
version = "0.6.9"
description = "Generate clients from an Open RPC document."
authors = ["Matthew Burkard <matthewjburkard@gmail.com>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
homepage = "https://gitlab.com/mburkard/openrpc-client-generator"
repository = "https://gitlab.com/mburkard/openrpc-client-generator"
keywords = ["openrpc", "jsonrpc", "generator"]
classifiers = ["Programming Language :: Python :: 3"]
packages = [
    { include = "openrpcclientgenerator", from = "src" },
]

[tool.poetry.build]
generate-setup-file = true

[tool.poetry.dependencies]
python = "^3.9"
build = "~0.7"
openrpc = "~1"
