[tool.poetry]
name = "openrpcclientgenerator"
version = "0.26.9"
description = "Generate clients from an Open RPC document."
readme = "README.md"
repository = "https://gitlab.com/mburkard/openrpc-client-generator"
homepage = "https://gitlab.com/mburkard/openrpc-client-generator"
license = "AGPL-3.0-or-later"
authors = ["Matthew Burkard <matthewjburkard@gmail.com>"]
classifiers = ["Programming Language :: Python :: 3"]

[tool.poetry.dependencies]
python = "^3.10"
case-switcher = "^1.2.1"
openrpc = "^5.0.3"
httpx = "^0.23.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
safety = "^2.2.0"
mypy = "^0.982"
flake8 = "^5.0.4"
coverage = "^6.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
