[tool.poetry]
name = "openrpcclientgenerator"
version = "0.25.1"
description = "Generate clients from an Open RPC document."
readme = "README.md"
repository = "https://gitlab.com/mburkard/openrpc-client-generator"
homepage = "https://gitlab.com/mburkard/openrpc-client-generator"
license = "AGPL-3.0-or-later"
authors = ["Matthew Burkard <matthewjburkard@gmail.com>"]
classifiers = ["Programming Language :: Python :: 3"]

[tool.poetry.dependencies]
python = "^3.10"
case-switcher = "^1.2.1"
openrpc = "^4.0.1"
build = "^0.7.0"
httpx = "^0.21.2"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
safety = "^1.10.3"
mypy = "^0.931"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
